New log file opened at Sat Feb 24 22:36:46 JST 2018 by 4948@MAIN
Taking next connection to: 49731
New client attempting to connect on port: 49732-49731
  Address = /192.168.3.101:49731
This client on port 49732 has uuid bce85a3f-0ed4-46cd-b35a-a9c71179e160 configName activator humanReadableName Activator protocolVersion 3 featureTags Vector()
Connected Clients: activator-bce85a3f-0ed4-46cd-b35a-a9c71179e160
Taking next connection to: 49731
New client attempting to connect on port: 49734-49731
  Address = /192.168.3.101:49731
Handshake exception on socket: 49734
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at java.io.DataInputStream.readInt(DataInputStream.java:387)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 49731
New client attempting to connect on port: 49735-49731
  Address = /192.168.3.101:49731
This client on port 49735 has uuid 0ad46710-6f0b-4309-882f-aac09a964d46 configName activator humanReadableName Activator protocolVersion 3 featureTags Vector()
Connected Clients: activator-bce85a3f-0ed4-46cd-b35a-a9c71179e160, activator-0ad46710-6f0b-4309-882f-aac09a964d46
Taking next connection to: 49731
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 49731
New client attempting to connect on port: 49750-49731
  Address = /192.168.3.101:49731
Handshake exception on socket: 49750
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at java.io.DataInputStream.readInt(DataInputStream.java:387)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 49731
New client attempting to connect on port: 49751-49731
  Address = /192.168.3.101:49731
This client on port 49751 has uuid df180fd6-1f3d-46c1-9ebc-b0fe6fc1f17e configName play-fork-run humanReadableName Play Fork Run protocolVersion 1 featureTags Vector()
Connected Clients: activator-bce85a3f-0ed4-46cd-b35a-a9c71179e160, play-fork-run-df180fd6-1f3d-46c1-9ebc-b0fe6fc1f17e
Taking next connection to: 49731
Checking to see if clients are empty...
No non-daemon clients connected after 3 min. Shutting down.
Server socket thread exiting.
0 clients open, will close them...
All client sockets have been closed.
Closing the 4948@MAIN logs at Sat Feb 24 22:45:11 JST 2018, goodbye.
